mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
import todo.views as todo

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', todo.hello_show),
    url(r'todo/', include('todo.urls'), name='todo')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

todo/urls.py
from django.conf.urls import url
import todo.views as todo

app_name = 'todo'

urlpatterns = [
    url(r'^$', todo.hello_show, name="hello_show"),
    url(r'^todo_list/$', todo.TodoListView.as_view(), name='todo_list'),
    url(r'^todo_add/$', todo.ToDoAddView.as_view(), name='todo_add'),
    url(r'^categories/$', todo.CategoriesView.as_view(), name='categories'),
    url(r'^categories/(?P<pk>[^/]+)/delete$', todo.ToDoCategoryDeleteView.as_view(), name='categories_delete')
]

todo/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=20)

    class Meta:
        verbose_name = 'kategoria'
        verbose_name_plural = 'kategorie'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('todo:categoryformadd')

class ToDo(models.Model):
    TODO = 'TD'
    DONE = 'DN'
    STATUS = (
        (TODO, 'Aktywny'),
        (DONE, 'Wykonane')
    )
    DIFFICULTY = (
        (1, 'Od ręki'),
        (3, 'Prosty'),
        (5, 'Średnie'),
        (8, 'Trudne'),
        (13, 'Bardzo trudne'),
    )

    name = models.CharField(max_length=250)
    description = models.TextField(verbose_name='Opis')
    date_created = models.DateField(auto_now_add=True)
    date_deadline = models.DateField(default=None)
    status = models.CharField(max_length=2, choices=STATUS)
    active = models.BooleanField(default=True)
    time_expected = models.IntegerField(default=15)
    difficulty = models.IntegerField(choices=DIFFICULTY)
    category = models.ForeignKey(Category)

    class Meta:
        verbose_name = 'zadanie'
        verbose_name_plural = 'zadania'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('todo:todoformadd')

todo/forms.py
from django import forms
from todo.models import ToDo, Category


class ToDoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ['name', 'description', 'date_deadline', 'status', 'time_expected', 'difficulty', 'category']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

class ChangeStatusForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ['status']

todo/views.py
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, CreateView, DetailView, TemplateView, FormView, DeleteView
from django.shortcuts import render, redirect
from todo.models import ToDo, Category
from todo.forms import ToDoForm, CategoryForm, ChangeStatusForm
from django.db.models import When, Count, Case, CharField


def hello_show(request):
    """ Welcome message page (django view can be function view or class based view)"""
    return render(request, 'todo/start.html', {})


class TodoListView(ListView):
    """ List display all user task """
    form_class = ChangeStatusForm
    model = ToDo
    template_name = 'todo/todo_list.html'

    def post(self, request, *args, **kwargs):
        """ If user clikg 'Gotowe!' button change task status to DONE and save """
        if request.POST.get('gotowe'):
            task_pk = request.POST.get('gotowe')
            task = self.model.objects.get(pk=task_pk)
            task.status = self.model.DONE
            task.save()

        return redirect('todo:todo_list')


class ToDoAddView(CreateView):
    """ User can add new taks to todolist """
    form_class = ToDoForm
    model = ToDo
    template_name = 'todo/todo_add.html'
    success_url = reverse_lazy('todo:todo_list')

class CategoriesView(FormView):
    """ Add new category page """
    model = Category
    form_class = CategoryForm
    context_object_name = 'category_list'
    template_name = 'todo/categories.html'
    success_url = reverse_lazy('todo:categories')

    def get_context_data(self, **kwargs):
        """
        you can pass to context everything you want display in django template
        :return dictionary
        """
        context = super().get_context_data(**kwargs)
        context['categorys_list'] = Category.objects.all()
        return context

    def form_valid(self, form):
        """
        save ModelForm here and back to success url,
        instead this you can use django View or TemplateView base class
        and do this in post method.
        :param form:
        :return: HttpResponse
        """
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        print('invaliddd')
        return super().form_invalid(form)


class ToDoCategoryDeleteView(DeleteView):
    """ Delete item on click delete button in CategoriesView """
    success_url = reverse_lazy('todo:categories')
    model = Category
    template_name = 'todo/category_delete.html'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content=""/>
    <title>H3S Django</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <link href="https://getbootstrap.com/examples/navbar/navbar.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]>
    <script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
<div class="container">
    {% include 'navbar.html' %}
    {% block navbar %}{% endblock %}
    <h1>Listy zadań ToDo</h1>
    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap core JavaScript
        ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
</div>
</body>
</html>

templates/navbar.html
{% block navbar %}
<!-- Static navbar -->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">H3S django</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">ToDo<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'todo:todo_list' %}">Listy Zadań</a></li>
                        <li><a href="{% url 'todo:todo_add' %}">Dodaj Zadanie</a></li>
                        <li><a href="{% url 'todo:categories' %}">Kategorie</a></li>
                    </ul>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>
<!-- End Static navbar -->
{% endblock navbar %}

todo/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content=""/>
    <title>H3S Django</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <link href="https://getbootstrap.com/examples/navbar/navbar.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]>
    <script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
<div class="container">
    {% include 'navbar.html' %}
    {% block navbar %}{% endblock %}
    <h1>TESTY!!!</h1>
    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap core JavaScript
        ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
</div>
</body>
</html>

todo/templates/todo.html
{% extends 'base.html' %}

{% block content %}
<p>Listy Zadań</p>

<ul>
    <table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Nazwa</th>
      <th>Kategoria</th>
      <th>Opis</th>
      <th>Status</th>
      <th>Data utworzenia</th>
      <th>Deadline</th>
        <th>DONE</th>
    </tr>
  </thead>
  <tbody>
  {% for todo in object_list %}
    <tr>
      <th scope="row">{{todo.id}}</th>
      <td>{{todo.name}}</td>
      <td>{{todo.category.name}}</td>
      <td>{{todo.description}}</td>
        <td>{% if todo.status == "TD" %}Do zrobienia{% else %}Gotowe!{% endif %}</td>
        <td>{{todo.date_created}}</td>
        <td>{{todo.date_deadline}}</td>
        <td>
            <form method="post">
                {% csrf_token %}
                <button type="submit" name="gotowe" value={{todo.pk}}>Gotowe</button>
            </form>
        </td>
    </tr>
      {{ todo.condi }}
  {% endfor %}
  </tbody>
</table>

</ul>

{% endblock %}

todo/templates/todo/categories.html
{% extends 'base.html' %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Add</button>
    </form>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>Nazwa</th>
            <th>Akcja</th>
        </tr>
        </thead>
        <tbody>
        {% for category in categorys_list %}
            <tr>
                <td>{{ category }}</td>
                <td>
                    <a href="{% url "todo:categories_delete" category.pk %}">X</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

todo/templates/todo/category_delete.html
{% extends 'base.html' %}

{% block content %}

    <div>
    Czy na pewno chcesz usunąć kategorie o naziwe: <b>{{ category }}</b>?
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Usuń</button>
    </form>

{% endblock content %}

todo/templates/todo/start.html
{% extends 'base.html' %}

{% block content %}

<p>Hello World!</p>
<p>Aplikacja do planowania zadań ToDo-Djano!</p>
<p>Wybierz opcje z menu rozwijanego na górze strony.</p>
{% endblock %}

todo/templates/todo/todo_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<form method="post" action="{% url "todo:todo_add" %}">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Send" />
</form>

{% endblock %}

todo/templates/todo/todo_list.html
{% extends 'base.html' %}

{% block content %}
<p>Listy Zadań</p>

<ul>
    <table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Nazwa</th>
      <th>Kategoria</th>
      <th>Opis</th>
      <th>Status</th>
      <th>Data utworzenia</th>
      <th>Deadline</th>
        <th>DONE</th>
    </tr>
  </thead>
  <tbody>
  {% for todo in object_list %}
    <tr>
      <th scope="row">{{todo.id}}</th>
      <td>{{todo.name}}</td>
      <td>{{todo.category.name}}</td>
      <td>{{todo.description}}</td>
        <td>{% if todo.status == "TD" %}Do zrobienia{% else %}Gotowe!{% endif %}</td>
        <td>{{todo.date_created}}</td>
        <td>{{todo.date_deadline}}</td>
        <td>
            <form method="post">
                {% csrf_token %}
                <button type="submit" name="gotowe" value={{todo.pk}}>Gotowe</button>
            </form>
        </td>
    </tr>
      {{ todo.condi }}
  {% endfor %}
  </tbody>
</table>

</ul>

{% endblock %}

todo/templates/todoform.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<form method="post" action="{% url "todo:todo_add" %}">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Send" />
</form>

{% endblock %}